spring.application.name=stats
# H2 Connection Setup
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# H2 Access Panel (Available at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
latestFXRateQuery=\
with windowed_rates as (select fx_rate, currency_from_id, currency_to_id, date, \
  row_number() over(partition by currency_from_id, currency_to_id order by date desc) rn from FX_Rates \
)
select * from windowed_rates where rn = 1 and currency_from_id = :fromId currency_to_id = :toId\

declingTrendQuery=\
  with reserve_stats as ( \
    select sum(pr.count) as total, sg.species_group_id as species_group_id, st.name as species_name, asv.survey_year as survey_year \
    FROM Population_Records pr \
    JOIN Annual_Surveys asv \
       ON pr.survey_id = asv.survey_id \
    JOIN Species_Groups sg \
       ON sg.species_group_id = pr.species_group_id \
    JOIN Species_Types st \
       ON st.species_type_id = sg.species_type_id \
group by  st.name, asv.survey_year, sg.species_group_id\
  ), \
lagged as ( \
     select *, \
         lag(total, 1) over (partition by species_group_id order by survey_year) prev1, \
         lag(total, 2) over (partition by species_group_id order by survey_year) prev2, \
         lag(total, 3) over (partition by species_group_id order by survey_year) prev3 \
     FROM reserve_stats \
) \
select species_name, survey_year from lagged where total < prev1 and prev1 < prev2 and prev2 < prev3
